config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :users
  resources :events

  get '/auth/:provider/callback', to: 'sessions#create'

  root to: "events#index"

  resources :events do
    member do
      put "like", to: "events#upvote"
    end
  end

end

app/models/event.rb
class Event < ActiveRecord::Base
  acts_as_votable
end

app/models/user.rb
class User < ActiveRecord::Base
  include Gravtastic
  gravtastic

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :omniauthable,
         :recoverable, :rememberable, :trackable, :validatable

  def self.find_or_create_from_auth_hash(auth_hash)
    user = where(provider: auth_hash.provider, uid: auth_hash.uid).first_or_create
    user.update(
      name: auth_hash.info.nickname,
      profile_image: auth_hash.info.image,
      token: auth_hash.credentials.token,
      secret: auth_hash.credentials.secret
    )
    user
  end

  def twitter
    @client ||= Twitter::REST::Client.new do |config|
      config.consumer_key        = Rails.application.secrets.twitter_api_key
      config.consumer_secret     = Rails.application.secrets.twitter_api_secret
      config.access_token        = '12752732-XEuh7ICu4l6BcSPNpRMXdVFoKFU3Wk1jSxBBm8h3f'
      config.access_token_secret = 'doiGQbG4frSWsWYdlfMRUGI17FUIjUPUCYdgoocJi2FDb'
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  def upvote

    @event = Event.find(params[:id])
    @event.upvote_by current_user
    redirect_to events_path

  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:date, :name, :description, :city, :accepted, :deit)
    end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def twitter
    user = User.twitter_auth(request.env["omniauth.auth"])
    sign_in_and_redirect user
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    @user = User.find_or_create_from_auth_hash(auth_hash)
    session[:user_id] = @user.id
    redirect_to root_path
  end

  protected

  def auth_hash
    request.env['omniauth.auth']
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def show
        @user = User.find(params[:id])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/omniauth_callbacks_helper.rb
module OmniauthCallbacksHelper
end

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_field :date %>
  </div>
    <div class="field">
    <%= f.label :deit %><br>
    <%= f.date_field :deit %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>

  <div class="field">
    <%= f.hidden_field :accepted, :value => '0' %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<div class=" col-md-12 daywrapper">
  <span class=""><%= Time.now.to_s(:short) %></span>
    <% @events.each do |event| %>
      <% if event.accepted == 0 %>
          <div class="row eventrow">
            <span class="eventlikes"><%= link_to '↑', like_event_path(event), method: :put %>9</span>
            <a href="/events/<%= event.id %>"><span class="eventtitle"><%= event.name %> | <%= event.city %></span></a>
            <div class="eventgoers right">
              <span class="">Submitted by</span><img src="http://i.imgur.com/Lpavq5s.png?1" class="individualeventgoer">
            </div>
          </div>
      <% else %>
          <div class="row eventrow red">
            <span class="eventlikes"><%= link_to '↑', like_event_path(event), method: :put %></span>
            <a href="/events/<%= event.id %>"><span class="eventtitle"><%= event.name %> | <%= event.city %></span><span class="">Only visible to admin</span></a>
            <div class="eventgoers right">
              <span class="">Submitted by</span><img src="http://i.imgur.com/Lpavq5s.png?1" class="individualeventgoer">
            </div>
          </div>
      <% end %>
    <% end %>
    <div class="showmoreday center">Show more</div>
</div>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<div class=" col-md-12 daywrapper">
  <span class=""><%= Time.now.to_s(:short) %></span>

      <% if @event.accepted == 0 %>
          <div class="row eventrow">
            <span class="eventlikes"><%= link_to '↑', like_event_path(@event), method: :put %>9</span>
            <a href="/events/<%= @event.id %>"><span class="eventtitle"><%= @event.name %> | <%= @event.city %></span></a>
            <div class="eventgoers right">
              <span class="">Submitted by</span><img src="http://i.imgur.com/Lpavq5s.png?1" class="individualeventgoer">
            </div>
          </div>
      <% else %>
          <div class="row eventrow red">
            <span class="eventlikes"><%= link_to '↑', like_event_path(@event), method: :put %>9</span>
            <a href="/events/<%= @event.id %>"><span class="eventtitle"><%= @event.name %> | <%= @event.city %></span><span class="">Only visible to admin</span></a>
            <div class="eventgoers right">
              <span class="">Submitted by</span><img src="http://i.imgur.com/Lpavq5s.png?1" class="individualeventgoer">
            </div>
          </div>
      <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>GoHive 2.0.</title>
  <meta name="description" content="You got software, I can help with the marketing" >
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
  <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <link rel="stylesheet" type="text/css" href="main.css">
  <link rel="shortcut icon" type="image/png" href=""/>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="mainheader">
    <div class="hivelogo left itemsleft">The New Hive</div>
    <span class="left itemsleft">About</span>
    <div class="cities left itemsleft"><img src="">Cities</div>
    <div class="submit right"><a href="/events/new" class="loginshortcuts">Add a new event</a></div>
    <% if current_user.present? %>
      <div class="right"><a href="/users/<%= current_user.id %>" class="loginshortcuts">hey <%= current_user.email %><%= image_tag current_user.gravatar_url, class: 'useravatar' %> </div>
      <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
    <% else %>
      <div class="right"><a href="/users/sign_in" class="loginshortcuts">Signup my friend!</a></div>
    <% end %>
    <div class="topbanner">
    <a href="/">Get the best of Brussels</a>
    <span >Bullshit free</span>
    </div>
  </div>

<div class="container">
<%= yield %>
</div>

</body>
</html>

app/views/users/show.html.erb
<h2>Events added by <%= @user.email %> </h2>
More stuff here